### ISSUE TITLE
ブラウザリロード時に強制的にTrackAに戻ってしまう

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-ui#144]

**Comment by oshiro3** [comment]
これって実装するとしたら設計的には SessionStorage とかで UI 側で状態を保持しておくのがよいんでしょうか？

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/179 で選択しているトラック情報を保持するようになったのでクローズ
