### ISSUE TITLE
Dreamkast側がログアウトしていてもUIが見れてしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-ui#157]
CODTのイベントで発生。

Dreamkast本体側で未ログインでもUIを表示でき、動画の視聴はできてしまう。
ただチャットは403で蹴られるので、投稿はできないし変な動きになる。

https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1630042019042500
↑こういうログがでていたようだが、401じゃなくて403なのはちょっと謎・・・

**Comment by jacopen** [comment]
これでChat APIを見てみて問題があったらトップページに遷移にしたはずなんだけど、これが動いていないっぽい？
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/54

**Comment by jacopen** [comment]
ログアウト状態でUIを表示すると、リクエストの方はちゃんと(?)エラーが返っているようにみえる。
![image](https://user-images.githubusercontent.com/79102/131848553-3107d7ce-f4a7-4863-ab84-951d9c21771b.png)

**Comment by jacopen** [comment]
エラーが返るのはいいけどchatのリクエストに対しては500?
と思ったので調べた。

内部的にはForbiddenという名前の500エラーが返っていた・・・
![image](https://user-images.githubusercontent.com/79102/131850911-69b66394-6926-4226-9fe7-5dd0fdd86db9.png)
![image](https://user-images.githubusercontent.com/79102/131850922-04cdbeb1-d824-41e6-9cf0-51cbfd4c72b9.png)

これは403を返そうとしてミスで500が帰っているのでdk側の問題

**Comment by jacopen** [comment]
500エラーが返る問題はDk側の修正で直せそう(あるべき403を返す)
が、ちょっと時間的に間に合わなさそうなので、今回は500帰ってきたらチャットNGと考えてリダイレクトって形にしてもらったほうがよさそう。

**Comment by jacopen** [comment]
https://github.com/cloudnativedaysjp/dreamkast/issues/674

これを入れると一旦このIssueの対処が不要になるというか、仕組みが変わってしまうので一旦このIssueクローズします。

**Comment by maktak1995** [comment]
マージされたのでcloseします
