### ISSUE TITLE
AdminのOnAir/Recording切り替え時、Dkの読み込み重たい

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-ui#230]
### 問題

セッション切替時、まとめてOnAirやRecordingを切り替えるとDkが重たくなり、カウントダウン中の1分以内に切り替えられない
特に、感覚値ではあるがRecordingを実行してから重たくなる。

**Comment by jacopen** [comment]
コードで言うとここ
https://github.com/cloudnativedaysjp/dreamkast-ui/blob/bfd3070bceada9b4bf29c03b7d7a57773f1f6356/src/components/Track/Track.tsx#L157

WebSocketでReceivedになった際にREST APIを叩いてTalk一覧を取りに行く仕組みになっているので、切り替わりが発生した瞬間視聴者が一斉にAPIを叩きに行ってしまう。

以前はバグで動いていなかったが、現在はWebsocketのMessageでTalk一覧が飛んで来ているので、それを使う形にしたほうがいいかもしれない
