### ISSUE TITLE
事前登録したセッションに自動的に遷移してほしい 

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-ui#359]

**Comment by hrk091** [comment]
事前登録セッションが開始したときにsnackbarで通知され、そこから対象セッションに移れるようにした。
同一スロットで複数セッションを登録している場合でも対応可能となっている。
現在の事前登録の仕様だと、自動遷移よりもこの方式の方がベターで考えられ、既に実装済みなため、本issueはcloseする。
