### ISSUE TITLE
コメントの削除機能が欲しい

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-ui#71]
今だとミスってても直す術が無い

**Comment by takaishi** [comment]
物理削除するとリプライの扱いが手間なので論理削除かなあ？

**Comment by takaishi** [comment]
- 以下のAPIを追加
  - ChatMessageの更新
  - 自身のProfileを返す
- 自分が投稿したチャットメッセージにDeleteボタンを追加する
