### ISSUE TITLE
チャットは改行できないようにしたい

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-ui#90]
現状チャットに改行を入れても表示上は反映されないので、ならばいっそのことFormで改行できないようにしたい
![image](https://user-images.githubusercontent.com/79102/109529746-5c5d5d00-7af9-11eb-9a7e-427c58feb65d.png)

**Comment by takaishi** [comment]
フォームのmultilineをdisableにしたら改行できなくなったけど、Enterで投稿できるようになったｗ

**Comment by jacopen** [comment]
つまりその修正だけで、これも #91  も同時に達成できるってことか。一石二鳥！
